"""First-party learning handbook; EPUB3 with accessible SVG and linked navigation."""
from pathlib import Path
from html import escape
import hashlib, json, re, zipfile
from xml.etree import ElementTree as ET

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT.parent/'deliverables/CWS_Hoc_Giao_Dich_Va_Bai_Hoc_Backtest_2026-10-05.epub'
chapters=[]
def add(title,text): chapters.append((title,text))
add('Bắt đầu từ đây: giao dịch là gì?','Bạn có thể nghĩ giao dịch giống việc mua một món hàng rồi bán lại. Bạn mua khi cho rằng giá sẽ tăng. Nếu giá tăng, bạn có thể bán và có lời. Nếu giá giảm, bạn có thể bị lỗ.\n\nTrong thị trường tài chính còn có cách giao dịch để kiếm lời khi giá giảm. Trên web của bạn, BUY nghĩa là đặt cược giá sẽ tăng; SELL nghĩa là đặt cược giá sẽ giảm. Đây là cách giải thích đơn giản. Khi dùng tiền thật, cách mua bán còn phụ thuộc sản phẩm và nhà môi giới.\n\nMột ‘lệnh’ là một lần giao dịch. ‘Lệnh đang mở’ nghĩa là lần giao dịch đó chưa kết thúc. ‘Đóng lệnh’ nghĩa là kết thúc và ghi nhận kết quả. Giá còn thay đổi thì kết quả của lệnh đang mở cũng còn thay đổi.\n\nHiện web CWS đang giao dịch thử, chưa dùng tiền thật. Hãy coi nó như phòng tập. Bạn quan sát cách bot chờ, vào và thoát, rồi học từ kết quả. Con số trên web không phải số tiền trong MT5.\n\nChỉ cần nhớ: BUY mong giá tăng. SELL mong giá giảm. Đang mở là chưa kết thúc. Đã đóng là đã kết thúc.\n\nTự kiểm tra: bot BUY ở giá 100, sau đó giá lên 105. Hướng đi đó có lợi hay bất lợi? Đáp án: có lợi, nhưng chưa nói được số tiền lời nếu chưa biết cách tính và chi phí.')
add('Không biết thì chờ: khi nào mới nên vào?','Không phải lúc nào cũng cần có lệnh mới. Giống như qua đường, nhìn thấy đường không có nghĩa là bước qua ngay. Bạn cần chờ lúc đủ điều kiện.\n\nVới giao dịch, ‘tín hiệu’ là dấu hiệu đã được quy định trước để cho phép vào lệnh. Không phải cảm giác ‘chắc sắp tăng’. Bot cần kiểm tra dữ liệu và thấy điều kiện phù hợp. Nếu chưa thấy thì nó chờ. Chờ cũng là làm đúng việc.\n\nBot của bạn đang canh Nasdaq 100, S&P 500, Dow Jones 30, vàng và dầu, cùng các thị trường đã có trong danh sách. Canh không có nghĩa là mua hoặc bán ngay. Vàng đang có lệnh thì bot theo dõi lệnh đó; nó không mở thêm chỉ vì bạn muốn thấy nhiều lệnh.\n\nBạn vừa yêu cầu đóng những lệnh cũ. Bot không nên lập tức mở lại y hệt chỉ vì hướng giá cũ vẫn còn. Bản hiện tại chờ dữ liệu mới và thay đổi của dấu hiệu đã theo dõi.\n\nChỉ cần nhớ: có điều kiện rõ ràng thì mới vào. Không có thì chờ. Ít lệnh không tự động nghĩa là bot bị hỏng.\n\nTự kiểm tra: web ghi ‘Chờ tín hiệu mới’. Bạn có cần bấm gì để ép bot mua không? Đáp án: không. Đó là trạng thái chờ bình thường.')
add('Nếu sai thì mất bao nhiêu?','Trước khi nghĩ sẽ lời bao nhiêu, hãy hỏi: nếu sai, mình dự định chịu mất bao nhiêu?\n\nVí dụ để học: bạn mua ở giá 100. Bạn đặt mốc thoát nếu giá xuống 96. Mốc đó gọi là ‘dừng lỗ’. Nó giúp bạn có kế hoạch khi giá đi ngược, thay vì ngồi mong giá quay lại.\n\nNhưng dừng lỗ không phải lời hứa rằng bạn chỉ mất đúng mức đã định. Giá có thể nhảy từ 97 xuống 94 mà không có cơ hội thoát ở 96. Khi đó, kết quả có thể xấu hơn kế hoạch.\n\n@FIG:stop.svg\n\nKhông dời mốc dừng lỗ xa hơn chỉ để tránh nhận thua. Nếu làm vậy, một lỗi nhỏ có thể thành lỗi lớn. Cũng không tăng tiền vào lệnh sau khi thua để cố gỡ cho nhanh.\n\nTrong ví dụ này, khoảng từ 100 xuống 96 là 4 điểm giá. Nó chưa cho biết số tiền lỗ. Muốn biết tiền còn cần biết bạn giao dịch bao nhiêu và sản phẩm được tính thế nào. Vì vậy sách không đổi kết quả mô phỏng của web thành tiền MT5.\n\nChỉ cần nhớ: trước khi vào, phải biết lúc nào sẽ thoát nếu sai.\n\nTự kiểm tra: mua ở 100, định thoát ở 96 nhưng giá nhảy xuống 94. Có thể mất nhiều hơn dự tính không? Đáp án: có.')
add('Đọc kết quả trên web: ‘R’ nghĩa là gì?','Đừng để chữ R làm bạn khó chịu. Trong sách này, ta gọi nó là ‘một phần rủi ro’.\n\nBạn mua ở 100 và dự định dừng lỗ ở 96. Khoảng 4 điểm đó là một phần rủi ro. Nếu thoát ở 104, bạn được một phần. Nếu thoát ở 108, bạn được hai phần. Nếu thoát ở 96, bạn mất một phần, trong giả định chưa có phí và giá không nhảy qua mốc.\n\nWeb viết +2 R thì bạn đọc là ‘được hai phần so với mức rủi ro ban đầu’. Web viết −1 R thì đọc là ‘mất một phần’. Chữ R giúp so sánh các lệnh có giá khác nhau.\n\nNó không phải USD, đồng Việt Nam hay phần trăm tài khoản. Bạn cũng không được cộng bốn lệnh +1 R rồi kết luận tài khoản đã tăng 4%. Đó là những cách tính khác nhau.\n\nNếu chưa quen, hãy đọc dấu trước: dấu cộng là đang có lợi; dấu trừ là đang bất lợi. Sau đó mới nhìn số phần. Nhớ kiểm tra thời điểm giá, vì bảng có thể đang dùng giá đã ghi trước đó.\n\nChỉ cần nhớ: R là thước đo theo rủi ro ban đầu, không phải tiền.\n\nTự kiểm tra: mua 100, dừng lỗ 96, thoát 108. Được mấy phần? Đáp án: hai phần, vì lời 8 điểm so với khoảng rủi ro 4 điểm.')
add('Thắng ít vẫn có thể lời; thắng nhiều vẫn có thể lỗ','Hãy dùng một ví dụ tiền hoàn toàn giả định. Mỗi lần thua, bạn mất 100.000 đồng. Mỗi lần thắng, bạn được 300.000 đồng.\n\nSau 10 lần, bạn thắng 3 lần và thua 7 lần. Ba lần thắng được 900.000 đồng. Bảy lần thua mất 700.000 đồng. Bạn còn lời 200.000 đồng trước phí. Bạn thắng ít hơn thua nhưng vẫn có thể lời vì mỗi lần thắng lớn hơn mỗi lần thua.\n\nĐổi ví dụ: thắng 7 lần nhưng mỗi lần chỉ được 30.000 đồng; thua 3 lần, mỗi lần mất 100.000 đồng. Bạn được 210.000 nhưng mất 300.000. Kết quả là lỗ 90.000 đồng trước phí, dù thắng nhiều hơn.\n\nĐó là lý do không thể chỉ hỏi ‘bot thắng bao nhiêu phần trăm?’. Cần hỏi thêm: một lần thắng được bao nhiêu, một lần thua mất bao nhiêu, và phí lấy đi bao nhiêu?\n\n@FIG:expectancy.svg\n\nBiểu đồ dùng đơn vị ‘phần’ đã giải thích ở chương trước. Nó chỉ minh họa phép tính, không phải kết quả của bot.\n\nChỉ cần nhớ: số lần thắng chưa đủ. Độ lớn của lần thắng, lần thua và chi phí đều quan trọng.\n\nTự kiểm tra: lời 200.000 đồng trước phí, nhưng tổng phí 200.000 đồng. Còn lời không? Đáp án: không, bằng không.')
add('‘Backtest’ là thử lại trên dữ liệu cũ','Từ backtest nghe khó, nhưng ý chính rất đơn giản: lấy giá đã xảy ra trong quá khứ để thử xem bộ quy tắc sẽ làm gì. Trong sách ta gọi là ‘thử trên dữ liệu cũ’.\n\nGiống như bạn tập lái bằng tình huống đã ghi lại. Bạn xem đến một thời điểm, quyết định, rồi mới xem điều gì xảy ra tiếp theo. Nếu xem hết tương lai trước rồi mới quyết định, kết quả sẽ đẹp nhưng không công bằng.\n\nKhi tạo quy tắc, ta dùng một phần dữ liệu để tìm cách làm. Sau đó phải thử trên phần dữ liệu khác chưa dùng để chọn cách đó. Nếu cách làm chỉ tốt trên phần đã xem, có thể nó chỉ hợp với chuyện đã xảy ra.\n\nCòn một câu hỏi: mức giá trên giấy có thật sự mua hoặc bán được không? Khi tính thêm phí, giá nhảy và giá mua bán khác nhau, kết quả có thể kém đi rất nhiều.\n\nCuốn sách này lấy bài học từ những kết quả cũ đã được ghi trong tài liệu CWS. Nó không nói rằng vừa chạy lại toàn bộ thị trường để tạo ra các số đó.\n\nChỉ cần nhớ: thử trên dữ liệu cũ là bước học, chưa phải bằng chứng chắc chắn kiếm tiền thật.\n\nTự kiểm tra: chọn cách giao dịch sau khi đã thấy toàn bộ kết quả, rồi dùng chính kết quả đó để khen cách mình chọn. Có công bằng không? Đáp án: không.')
add('Bài học từ vàng: một lần thắng lớn có thể che nhiều vấn đề','Tài liệu CWS từng ghi một lần thử vàng có tổng lời khoảng 116 phần. Nghe rất đẹp. Nhưng riêng lần thắng lớn nhất đã đem lại khoảng 113 phần.\n\nBỏ lần thắng lớn nhất, tổng chỉ còn gần 4 phần. Bỏ ba lần thắng lớn nhất, kết quả chuyển thành lỗ khoảng 14 phần. Khi thử một cách tính giá vào và giá thoát thực tế hơn, kết quả cũng chuyển sang lỗ.\n\n@FIG:gold.svg\n\nNhững cột này là các cách thử khác nhau được ghi trong tài liệu, không phải kết quả nối tiếp của một tài khoản. Số có dấu cộng là lời theo cách tính đó; số có dấu trừ là lỗ. Các số chưa phải tiền và không dự báo tương lai.\n\nBài học không phải ‘đừng bao giờ giao dịch vàng’. Bài học là: đừng chỉ nhìn tổng lời. Hãy hỏi xem tổng đó có dựa quá nhiều vào một lần may mắn hoặc một giả định quá dễ hay không.\n\nMột cách giao dịch theo xu hướng có thể cần vài lần thắng lớn. Vì vậy cũng không nên đóng mọi lệnh lời quá sớm chỉ để cảm thấy an tâm. Ta cần thử cả hai điều: giữ cơ hội lời lớn và chịu được những lần thua trước đó.\n\nChỉ cần nhớ: kết quả đẹp phải chịu được câu hỏi khó.\n\nTự kiểm tra: tổng lời 116 phần, một lệnh lời gần 113 phần. Hệ thống đã được chứng minh bền vững chưa? Đáp án: chưa, cần thêm kiểm tra.')
add('Bài học từ Bitcoin và các chỉ số','Tài liệu CWS ghi một lần thử Bitcoin lời gần 10 phần. Nhưng bỏ lần thắng lớn nhất thì chỉ còn chưa tới một phần. Bỏ ba lần thắng lớn nhất thì thành lỗ gần 14 phần.\n\n@FIG:btc.svg\n\nNghĩa là kết quả phụ thuộc nhiều vào vài lần thắng lớn. Không nên lấy con số lời cũ rồi mong tháng sau sẽ lặp lại.\n\nVới các chỉ số, tài liệu cũng ghi có trường hợp cách giao dịch nhìn tốt ở một giai đoạn nhưng kém khi thử qua nhiều giai đoạn khác. Khi kết quả không thống nhất, hãy chờ thêm bằng chứng, thay vì chỉ chọn con số dễ thích.\n\nNasdaq 100, S&P 500 và Dow Jones 30 đều theo dõi nhóm cổ phiếu Mỹ, nhưng không giống nhau. Nếu mua cả ba cùng lúc, bạn có thể vẫn đang đặt cược vào một hướng chung của thị trường Mỹ. Có ba lệnh không có nghĩa là rủi ro đã được chia ra hoàn toàn.\n\nGiá vàng và dầu của phòng thử dùng sản phẩm đại diện. Chúng chưa phải đúng sản phẩm trong tài khoản MT5 của bạn. Vì vậy không lấy kết quả trong phòng thử làm số tiền lãi thật.\n\nChỉ cần nhớ: nhiều thị trường không tự động nghĩa là ít rủi ro. Kết quả cũ không phải lời hứa.\n\nTự kiểm tra: ba chỉ số Mỹ cùng giảm, ba lệnh mua có thể cùng lỗ không? Đáp án: có.')
add('Vì sao đường lợi nhuận không thể luôn đi lên?','Bạn có thể làm đúng quy tắc mà vẫn gặp nhiều lần thua liên tiếp. Thị trường không biết và không quan tâm bạn cần thắng vào hôm nay.\n\nTrong hình dưới, số vốn là ví dụ tự tạo. Nó lên 110, xuống 95 rồi mới lên lại. Đoạn từ đỉnh xuống đáy gọi là ‘mức sụt giảm’. Bạn chưa cần nhớ từ chuyên môn nào khác.\n\n@FIG:drawdown.svg\n\nTừ 110 xuống 95 là giảm khoảng 13,6%. Để từ 95 quay về 110, cần tăng khoảng 15,8%. Vì vốn đã nhỏ đi, phần trăm cần kiếm lại lớn hơn phần trăm vừa mất.\n\nHình vẽ có đoạn hồi phục để bạn dễ hình dung. Ngoài đời không có bảo đảm rằng vốn sẽ hồi phục. Một phương pháp từng có lời vẫn có thể ngừng hiệu quả.\n\nKhi gặp chuỗi thua, việc đầu tiên là kiểm tra: bot có làm đúng luật không, dữ liệu có lỗi không, phí có quá cao không? Không phải tăng tiền để gỡ hoặc bỏ mốc dừng lỗ.\n\nChỉ cần nhớ: đừng đòi mỗi lệnh đều thắng hay vốn luôn tăng đều. Điều quan trọng là biết mình đang chịu rủi ro gì và có bằng chứng gì.\n\nTự kiểm tra: tài khoản ví dụ giảm từ 100 xuống 50. Tăng 50% từ 50 chỉ lên 75, chưa về 100. Muốn về 100 phải tăng 100%.')
add('Bot của bạn làm gì và bạn nên học thế nào?','Bạn có thể coi bot như người làm theo một tờ hướng dẫn. Nó không cần ChatGPT ngồi nhìn từng lệnh. Máy chủ chạy kiểm tra theo lịch, rồi làm theo quy tắc đã viết.\n\nBản hiện tại xem ba dấu hiệu của xu hướng giá. Khi được phép mở, nó đặt mốc dừng lỗ theo độ dao động của giá. Nó có thể thoát khi chạm mốc hoặc khi dấu hiệu đổi hướng. Nó chưa có cách tự kéo mốc dừng lỗ theo giá đang chạy. Những ý tưởng khác từ sách còn phải thử, không phải cứ có trong sách là bot đã làm được.\n\n@FIG:workflow.svg\n\nBạn chỉ cần nhìn ba nơi trên web: ‘Đang canh’ cho biết bot có chờ không; ‘Vị thế đang mở’ cho biết lệnh chưa kết thúc; ‘Lịch sử’ cho biết lệnh đã kết thúc và lý do. ‘Theo yêu cầu’ nghĩa là bạn đã yêu cầu đóng, không phải bot tự tìm thấy lý do mới.\n\nKhi học, hãy bắt đầu bằng một lệnh. Viết: tại sao vào, nếu sai thì thoát ở đâu, giá được ghi lúc nào, kết thúc vì sao. Sau đó xem một nhóm lệnh để tìm điều lặp lại. Đừng đổi luật vì chỉ một lần thua.\n\nChỉ cần nhớ: bot làm theo luật, không phải phép màu. Bạn học để hiểu và kiểm tra luật đó.\n\nTự kiểm tra: đã đọc nhiều sách có nghĩa là bot chắc chắn có lời không? Đáp án: không. Ý tưởng từ sách còn cần được thử công bằng.')
add('Tờ ghi nhớ: trước và sau một lệnh','Trước khi vào, hỏi năm câu.\n\n1. Vì sao định vào lệnh này?\n2. Điều kiện vào đã xuất hiện chưa, hay mình chỉ đang nôn nóng?\n3. Nếu sai, mình sẽ thoát lúc nào?\n4. Mình có thể chịu mức mất dự định không?\n5. Đây là giao dịch thử hay giao dịch bằng tiền thật?\n\nSau khi kết thúc, hỏi bốn câu.\n\n1. Có làm đúng điều đã định không?\n2. Vì sao lệnh kết thúc?\n3. Có phải mình đã đổi luật vì sợ hoặc muốn gỡ không?\n4. Mình cần kiểm tra thêm điều gì?\n\nMột lệnh lỗ nhưng làm đúng kế hoạch chưa chắc là một quyết định tồi. Một lệnh lời nhưng vào tùy hứng cũng chưa chắc là một quyết định tốt. Đừng để một kết quả làm mình học nhầm.\n\nNếu đọc đến đây vẫn thấy rối, chỉ nhớ bốn điều: chưa có tín hiệu thì chờ; biết lúc nào thoát nếu sai; đừng tăng tiền để gỡ; kết quả đẹp cần được kiểm tra lại.\n\nBài tập cuối: mở web, chọn một dòng đang chờ và giải thích bằng lời của bạn vì sao chưa có lệnh. Sau đó chọn một lệnh đã đóng và đọc lý do. Bạn không cần đặt thêm lệnh để làm bài tập.')
add('Sách này lấy kiến thức từ đâu?','Bản này viết lại bằng lời đơn giản từ bản tổng hợp kiến thức CWS Trading Masterbook V3, các nguyên tắc đã lưu trong dự án và mã bot đang chạy ngày 05/10/2026. Các tài liệu dự án có tên sách và tác giả để truy nguồn; không có nghĩa là bot đã nạp toàn văn tất cả những cuốn đó.\n\nCác bài học về vàng và Bitcoin dùng kết quả cũ được ghi trong bản tổng hợp CWS. Chưa chạy lại các lần thử đó khi viết bản dễ hiểu này. Hình về phí, dừng lỗ và mức sụt giảm là ví dụ tự tạo để học, không phải thành tích của tài khoản.\n\nSách giữ lại ý chính của kiến thức: biết mình có thể mất bao nhiêu; chờ điều kiện rõ; không gỡ lỗ bằng cách tăng tiền; để cơ hội tốt có khoảng trống phát triển; ghi lý do của từng lệnh; và kiểm tra lại một phương pháp trước khi tin nó.\n\nNhững nguyên tắc đó không bảo đảm mọi lệnh thắng. Chúng giúp bạn hiểu điều đang làm và nhận ra chỗ chưa có bằng chứng.\n\nBiên soạn: Duy Trần – Founder CWS. Bản dành cho người mới. Không chép toàn văn sách thương mại, không chứa mật khẩu hay thông tin đăng nhập.')

def markdown(text):
    out=[]
    for block in re.split(r'\n\s*\n',text.strip()):
        if block.startswith('@FIG:'):
            name=block[5:].strip();out.append(f'<figure><img src="images/{name}" alt="{escape(figure_alt[name])}"/><figcaption>{escape(figure_alt[name])}</figcaption></figure>')
        elif block.startswith('#'):
            lines=block.splitlines()
            for line in lines:
                m=re.match(r'^(#{1,6})\s+(.*)',line)
                if m: out.append(f'<h{min(len(m[1])+1,6)}>{escape(m[2])}</h{min(len(m[1])+1,6)}>')
                elif line:out.append('<p>'+escape(line)+'</p>')
        else:out.append('<p>'+escape(block).replace('\n','<br/>')+'</p>')
    return '\n'.join(out)

figure_alt={'expectancy.svg': 'VÍ DỤ ĐỂ HỌC: thắng ít vẫn có thể lời nếu mỗi lần thắng lớn hơn mỗi lần thua. Phí có thể lấy hết phần lời.', 'stop.svg': 'VÍ DỤ ĐỂ HỌC: mua ở 100, định thoát ở 96; nếu giá nhảy xuống 94, có thể mất nhiều hơn dự định.', 'gold.svg': 'KẾT QUẢ CŨ TRONG TÀI LIỆU CWS: vàng nhìn có lời lớn, nhưng bỏ vài lần thắng lớn hoặc đổi cách tính giá thì kết quả kém đi. Đơn vị: phần rủi ro, không phải tiền.', 'btc.svg': 'KẾT QUẢ CŨ TRONG TÀI LIỆU CWS: Bitcoin phụ thuộc nhiều vào vài lần thắng lớn. Đây không phải lời hứa cho tương lai. Đơn vị: phần rủi ro.', 'drawdown.svg': 'VÍ DỤ ĐỂ HỌC: vốn từ 110 xuống 95; mất khoảng 13,6%, cần tăng khoảng 15,8% để quay lại 110. Không có bảo đảm sẽ hồi phục.', 'workflow.svg': 'CÁCH BOT ĐANG LÀM: kiểm tra giá, chờ dữ liệu đủ điều kiện, tìm dấu hiệu mới; chưa đủ thì đứng ngoài.'}
def svg(body):return '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="430" viewBox="0 0 800 430"><rect width="800" height="430" fill="#f8fafc"/><g font-family="sans-serif" fill="#142b45">'+body+'</g></svg>'
def txt(x,y,s,size=19):return f'<text x="{x}" y="{y}" font-size="{size}">{escape(s)}</text>'
def bars(title,items,scale):
    body=txt(25,36,title,24)+'<line x1="430" y1="65" x2="430" y2="385" stroke="#9aabba"/>'
    for i,(label,value) in enumerate(items):
        y=85+i*70;w=abs(value)*scale;x=430 if value>=0 else 430-w
        body+=txt(25,y+20,label,14)+f'<rect x="{x}" y="{y}" width="{w}" height="30" fill="'+('#087f75' if value>=0 else '#bf455a')+'"/>'+txt(665,y+23,f'{value:+.2f} phần',14)
    return svg(body)

def build():
    figures={
      'expectancy.svg':bars('Thắng, thua và phí · ví dụ để học',[('Thắng 3/10 lần, lời lớn hơn lỗ',.2),('Sau mức phí nhỏ',.05),('Sau mức phí lớn',-.05)],900),
      'gold.svg':bars('Vàng · kết quả cũ được ghi trong tài liệu',[('Cách thử ban đầu',116.17),('Bỏ lần thắng lớn nhất',3.6),('Bỏ ba lần thắng lớn',-14.22),('Thử giá thực tế hơn',-99.15)],2),
      'btc.svg':bars('Bitcoin · vài lần thắng lớn quyết định nhiều',[('Cách thử ban đầu',9.73),('Bỏ lần thắng lớn nhất',.62),('Bỏ ba lần thắng lớn',-13.6)],18),
      'stop.svg':svg(txt(25,35,'Giá và mốc dừng lỗ · ví dụ để học',24)+''.join(f'<line x1="250" y1="{y}" x2="680" y2="{y}" stroke="{color}"/>'+txt(25,y+6,label,17) for y,label,color in [(95,'108: được 2 phần','#087f75'),(220,'100: giá mua','#2978b7'),(280,'96: dừng lỗ','#bf455a'),(335,'94: giá nhảy xuống','#bf455a')])+txt(170,395,'Lên 108 không bắt buộc phải bán ngay.',18)),
      'drawdown.svg':svg(txt(25,35,'Vốn tăng rồi giảm · hình hoàn toàn minh họa',24)+'<polyline points="60,240 145,180 230,120 315,205 400,300 485,250 570,190 660,95" fill="none" stroke="#2978b7" stroke-width="4"/>'+txt(230,95,'Đỉnh 110')+txt(375,330,'Đáy 95')+txt(35,385,'Giảm 13,64% · cần hồi 15,79% để trở lại 110.',20)),
      'workflow.svg':svg(txt(25,35,'Bot chờ đúng lúc · không ép vào lệnh',24)+''.join(f'<rect x="40" y="{70+i*57}" width="710" height="42" rx="8" fill="#e5edf6"/>'+txt(55,98+i*57,t,18) for i,t in enumerate(['1. Kiểm tra dữ liệu giá có đủ và còn dùng được không','2. Chưa dùng dữ liệu của ngày còn đang diễn ra','3. Xem các dấu hiệu giá đang tăng hay giảm','4. Sau khi bạn đóng: chờ dữ liệu và dấu hiệu mới','5. Đủ điều kiện: giao dịch thử; chưa đủ: tiếp tục chờ'])))
    }
    files={'mimetype':b'application/epub+zip','META-INF/container.xml':b'<?xml version="1.0"?><container xmlns="urn:oasis:names:tc:opendocument:xmlns:container" version="1.0"><rootfiles><rootfile full-path="EPUB/package.opf" media-type="application/oebps-package+xml"/></rootfiles></container>'}
    css='body{font-family:serif;line-height:1.6;margin:5%;color:#142b45}h1,h2,h3{font-family:sans-serif;color:#174b71}p{text-align:left}img{width:100%;height:auto}figure{margin:1em 0}figcaption{font-size:.85em;color:#44566a}nav li{margin:.5em 0}h1{break-before:page}'
    files['EPUB/style.css']=css.encode()
    manifest=['<item id="css" href="style.css" media-type="text/css"/>'];spine=[];toc=[]
    def xhtml(title,body):return ('<?xml version="1.0" encoding="utf-8"?><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="vi" xml:lang="vi"><head><title>'+escape(title)+'</title><link rel="stylesheet" href="style.css"/></head><body>'+body+'</body></html>').encode()
    for i,(title,text) in enumerate(chapters):
        name=f'ch{i+1:02}.xhtml';cid=f'c{i+1}'
        files['EPUB/'+name]=xhtml(title,'<h1>'+escape(title)+'</h1>'+markdown(text))
        manifest.append(f'<item id="{cid}" href="{name}" media-type="application/xhtml+xml"/>');spine.append(f'<itemref idref="{cid}"/>');toc.append(f'<li><a href="{name}">{escape(title)}</a></li>')
    for name,content in figures.items():
        files['EPUB/images/'+name]=content.encode();manifest.append(f'<item id="img{len(manifest)}" href="images/{name}" media-type="image/svg+xml"/>')
    files['EPUB/nav.xhtml']=xhtml('Mục lục','<h1>CWS · Học giao dịch từ con số không</h1><p>Duy Trần – Founder CWS · 05/10/2026</p><nav epub:type="toc" id="toc"><h2>Mục lục</h2><ol>'+''.join(toc)+'</ol></nav>')
    manifest.append('<item id="nav" href="nav.xhtml" properties="nav" media-type="application/xhtml+xml"/>')
    files['EPUB/package.opf']=('''<?xml version="1.0" encoding="utf-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="bookid"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="bookid">urn:cws:learning:20261005:beginner-v2</dc:identifier><dc:title>CWS – Học giao dịch từ con số không</dc:title><dc:creator>Duy Trần – Founder CWS</dc:creator><dc:language>vi</dc:language><dc:description>Bản dễ hiểu cho người mới; 12 chương ngắn, 6 hình minh họa và bài học từ thử nghiệm cũ.</dc:description><meta property="dcterms:modified">2026-10-05T12:00:00Z</meta></metadata><manifest>'''+''.join(manifest)+'</manifest><spine><itemref idref="nav"/>'+''.join(spine)+'</spine></package>').encode()
    OUT.parent.mkdir(parents=True,exist_ok=True)
    with zipfile.ZipFile(OUT,'w') as z:
        for name,data in files.items():z.writestr(name,data,compress_type=zipfile.ZIP_STORED if name=='mimetype' else zipfile.ZIP_DEFLATED)
    with zipfile.ZipFile(OUT) as z:
        assert z.testzip() is None and z.infolist()[0].filename=='mimetype' and z.infolist()[0].compress_type==zipfile.ZIP_STORED
        for name in z.namelist():
            if name.endswith(('.xhtml','.opf','.svg','.xml')):
                tree=ET.fromstring(z.read(name))
                for e in tree.iter():
                    for k in ('href','src'):
                        link=e.get(k)
                        if link and '://' not in link:
                            target=(Path(name).parent/link.split('#')[0]).as_posix()
                            assert target in z.namelist(),(name,target)
            if name.endswith('.xhtml'):assert '\ufffd' not in z.read(name).decode()
    print(json.dumps({'file':str(OUT),'chapters':len(chapters),'figures':len(figures),'bytes':OUT.stat().st_size,'validation':'ZIP/XML/internal links/Vietnamese text PASS'},ensure_ascii=False))
if __name__=='__main__':build()
