create table if not exists ai_trade.training_replay_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  strategy_id text not null,
  universe_size integer not null,
  target_trades_per_symbol integer not null,
  completed_trades integer not null default 0,
  symbols_with_target integer not null default 0,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists ai_trade.training_replay_trades (
  id bigint generated by default as identity primary key,
  run_key text not null,
  strategy_id text not null,
  symbol text not null,
  asset_class text not null,
  sequence_no integer not null,
  direction text not null check (direction in ('UP','DOWN')),
  entry_ts timestamptz not null,
  exit_ts timestamptz not null,
  entry_price numeric not null,
  exit_price numeric not null,
  initial_stop numeric not null,
  gross_r numeric not null,
  r_10bps numeric not null,
  r_20bps numeric not null,
  exit_reason text not null,
  lesson_code text not null,
  created_at timestamptz not null default now(),
  unique(run_key,symbol,sequence_no)
);

create index if not exists training_replay_symbol_run_idx
  on ai_trade.training_replay_trades(run_key,symbol,sequence_no);

create table if not exists ai_trade.training_replay_lessons (
  id bigint generated by default as identity primary key,
  run_key text not null,
  strategy_id text not null,
  scope text not null check (scope in ('SYMBOL','PORTFOLIO')),
  symbol text,
  trade_count integer not null,
  wins integer not null,
  losses integer not null,
  net_r_10bps numeric not null,
  avg_r_10bps numeric not null,
  max_loss_r numeric not null,
  stop_exit_count integer not null,
  reversal_exit_count integer not null,
  lesson text not null,
  created_at timestamptz not null default now(),
  unique(run_key,scope,symbol)
);

revoke all on ai_trade.training_replay_runs from anon,authenticated;
revoke all on ai_trade.training_replay_trades from anon,authenticated;
revoke all on ai_trade.training_replay_lessons from anon,authenticated;
