create table if not exists ai_trade.mt5_demo_onboarding_tokens (
  id bigint generated by default as identity primary key,
  token_hash bytea not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

revoke all on ai_trade.mt5_demo_onboarding_tokens from public, anon, authenticated;

comment on table ai_trade.mt5_demo_onboarding_tokens is
  'One-time high-entropy tokens for securely storing user-created MT5 DEMO credentials without placing passwords in chat.';
