create extension if not exists pgcrypto;

create table if not exists ai_trade.mt5_demo_secret (
  id integer primary key check (id=1),
  key_text text not null,
  created_at timestamptz not null default now()
);

insert into ai_trade.mt5_demo_secret(id,key_text)
values (1, encode(gen_random_bytes(32),'hex'))
on conflict (id) do nothing;

create table if not exists ai_trade.mt5_demo_accounts (
  id bigint generated by default as identity primary key,
  provider text not null default 'METAQUOTES',
  server text not null default 'MetaQuotes-Demo',
  login bigint not null unique,
  password_cipher bytea not null,
  investor_password_cipher bytea,
  server_build integer,
  account_mode text not null default 'DEMO',
  verified boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  last_verified_at timestamptz
);

revoke all on ai_trade.mt5_demo_secret from public, anon, authenticated;
revoke all on ai_trade.mt5_demo_accounts from public, anon, authenticated;

comment on table ai_trade.mt5_demo_accounts is
  'Encrypted credentials for generic MetaQuotes DEMO accounts only. Never live/funded.';
