create table if not exists ai_trade.compliance_intents (
  id bigint generated by default as identity primary key,
  strategy_id text not null,
  symbol text not null,
  bar_stamp timestamptz not null,
  action text not null,
  visible_stop boolean not null,
  approval_verified boolean not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (strategy_id, symbol, bar_stamp)
);

comment on table ai_trade.compliance_intents is
  'Durable one-intent-per-closed-bar reservation for prop-firm compliance. No human-impersonation timing.';
