create table if not exists ai_trade.forward_shadow_state (
  strategy_id text not null,
  symbol text not null,
  asset_class text not null,
  last_processed timestamptz not null,
  last_review_month text not null,
  pending_direction text,
  position jsonb,
  warmed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (strategy_id, symbol),
  check (pending_direction is null or pending_direction in ('UP','DOWN'))
);

create table if not exists ai_trade.forward_shadow_trades (
  id bigint generated by default as identity primary key,
  strategy_id text not null,
  symbol text not null,
  asset_class text not null,
  direction text not null check (direction in ('UP','DOWN')),
  entry_ts timestamptz not null,
  exit_ts timestamptz not null,
  entry_price numeric not null,
  exit_price numeric not null,
  initial_stop numeric not null,
  risk_price numeric not null check (risk_price > 0),
  gross_r numeric not null,
  r_10bps numeric not null,
  r_20bps numeric not null,
  exit_reason text not null,
  created_at timestamptz not null default now(),
  unique (strategy_id, symbol, entry_ts, exit_ts)
);

create table if not exists ai_trade.forward_shadow_runs (
  id bigint generated by default as identity primary key,
  strategy_id text not null,
  request_id text,
  status text not null,
  result jsonb not null,
  created_at timestamptz not null default now()
);

comment on table ai_trade.forward_shadow_trades is
  'Forward-only research trades. Historical bars may warm indicators but may never be backfilled as trades.';
