create table if not exists ai_trade.backtest_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  strategy_id text not null,
  requested_start date not null,
  requested_end date not null,
  universe_size integer not null,
  result jsonb not null,
  created_at timestamptz not null default now()
);

comment on table ai_trade.backtest_runs is
  'Immutable cloud research evidence for historical multi-market backtests; never an execution approval by itself.';
