create table if not exists ai_trade.shadow_broker_orders (
  id bigint generated by default as identity primary key,
  client_order_id text not null unique,
  strategy_id text not null,
  symbol text not null,
  bar_ts timestamptz not null,
  action text not null check (action in ('ENTRY','EXIT')),
  side text not null check (side in ('BUY','SELL')),
  requested_price numeric not null check (requested_price > 0),
  fill_price numeric not null check (fill_price > 0),
  stop_price numeric,
  visible_stop boolean not null default false,
  synthetic_volume numeric not null default 1 check (synthetic_volume > 0),
  status text not null default 'FILLED' check (status in ('FILLED','FLAGGED')),
  compliance_state text not null default 'OK',
  source_trade_id bigint,
  reason text,
  broker_orders boolean not null default false check (broker_orders = false),
  live_money_locked boolean not null default true check (live_money_locked = true),
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists shadow_broker_orders_strategy_symbol_bar_idx
  on ai_trade.shadow_broker_orders(strategy_id,symbol,bar_ts);

create table if not exists ai_trade.shadow_broker_positions (
  strategy_id text not null,
  symbol text not null,
  direction text not null check (direction in ('UP','DOWN')),
  entry_ts timestamptz not null,
  entry_price numeric not null check (entry_price > 0),
  stop_price numeric not null check (stop_price > 0),
  synthetic_volume numeric not null default 1 check (synthetic_volume > 0),
  source_client_order_id text not null,
  updated_at timestamptz not null default now(),
  primary key(strategy_id,symbol)
);

create table if not exists ai_trade.shadow_broker_runs (
  id bigint generated by default as identity primary key,
  strategy_id text not null,
  status text not null,
  orders_inserted integer not null default 0,
  positions_open integer not null default 0,
  flagged_bars integer not null default 0,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

revoke all on ai_trade.shadow_broker_orders from anon, authenticated;
revoke all on ai_trade.shadow_broker_positions from anon, authenticated;
revoke all on ai_trade.shadow_broker_runs from anon, authenticated;

do $$
declare j bigint;
begin
  select jobid into j from cron.job
  where jobname='ai-trade-shadow-broker-reconcile-daily'
  limit 1;
  if j is not null then
    perform cron.unschedule(j);
  end if;
end $$;

select cron.schedule(
  'ai-trade-shadow-broker-reconcile-daily',
  '20 3 * * *',
  $cron$
  select net.http_post(
    url := 'https://oziktadfeenydvgobudr.supabase.co/functions/v1/ai-trade-shadow-broker-reconcile',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'x-ai-trade-cron',(select secret from ai_trade.cron_auth where id=1)
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 60000
  ) as request_id;
  $cron$
);
