create table if not exists ai_trade.robustness_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  strategy_id text not null,
  result jsonb not null,
  created_at timestamptz not null default now()
);

comment on table ai_trade.robustness_runs is
  'Reproducible research-only robustness evidence: long-history, parameter sensitivity, regimes, cost stress, and Monte Carlo. Never an execution approval.';
