create table if not exists ai_trade.dashboard_access_tokens (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  label text not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

revoke all on ai_trade.dashboard_access_tokens from anon, authenticated;
