create table if not exists ai_trade.forward_trade_journal (
  id bigint generated by default as identity primary key,
  source_trade_id bigint not null unique references ai_trade.forward_shadow_trades(id) on delete cascade,
  strategy_id text not null,
  trade_id text not null unique,
  symbol text not null,
  direction text not null check (direction in ('UP','DOWN')),
  entry_ts timestamptz not null,
  exit_ts timestamptz not null,
  r_10bps numeric not null,
  result_label text not null check (result_label in ('WIN','LOSS','FLAT')),
  setup text not null,
  entry_reason text not null,
  exit_reason text not null,
  lesson text not null,
  chart_timeframe text not null default '1h',
  tags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists forward_trade_journal_strategy_exit_idx
  on ai_trade.forward_trade_journal(strategy_id,exit_ts desc);

revoke all on ai_trade.forward_trade_journal from anon,authenticated;

do $$
declare j bigint;
begin
  select jobid into j from cron.job where jobname='ai-trade-journal-update-daily' limit 1;
  if j is not null then perform cron.unschedule(j); end if;
end $$;

select cron.schedule(
  'ai-trade-journal-update-daily',
  '30 3 * * *',
  $cron$
  select net.http_post(
    url := 'https://oziktadfeenydvgobudr.supabase.co/functions/v1/ai-trade-journal-update',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'x-ai-trade-cron',(select secret from ai_trade.cron_auth where id=1)
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 60000
  );
  $cron$
);
