create table if not exists ai_trade.training_arena_positions (
  strategy_id text not null,
  symbol text not null,
  asset_class text not null,
  direction text not null check (direction in ('UP','DOWN')),
  entry_ts timestamptz not null,
  entry_price numeric not null,
  stop_price numeric not null,
  risk_price numeric not null check (risk_price > 0),
  last_mark_ts timestamptz not null,
  last_mark_price numeric not null,
  unrealized_r numeric not null default 0,
  opened_reason text not null,
  updated_at timestamptz not null default now(),
  primary key(strategy_id,symbol)
);

create table if not exists ai_trade.training_arena_trades (
  id bigint generated by default as identity primary key,
  strategy_id text not null,
  symbol text not null,
  asset_class text not null,
  direction text not null check (direction in ('UP','DOWN')),
  entry_ts timestamptz not null,
  exit_ts timestamptz not null,
  entry_price numeric not null,
  exit_price numeric not null,
  initial_stop numeric not null,
  risk_price numeric not null,
  gross_r numeric not null,
  r_10bps numeric not null,
  r_20bps numeric not null,
  exit_reason text not null,
  created_at timestamptz not null default now(),
  unique(strategy_id,symbol,entry_ts,exit_ts)
);

create table if not exists ai_trade.training_arena_journal (
  id bigint generated by default as identity primary key,
  strategy_id text not null,
  symbol text not null,
  event_type text not null check (event_type in ('OPEN','MARK','CLOSE','REVERSE')),
  event_ts timestamptz not null,
  direction text check (direction in ('UP','DOWN')),
  price numeric,
  stop_price numeric,
  realized_r numeric,
  unrealized_r numeric,
  setup text not null,
  reason text not null,
  lesson text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists training_arena_journal_symbol_ts_idx
  on ai_trade.training_arena_journal(strategy_id,symbol,event_ts desc);

create table if not exists ai_trade.training_arena_runs (
  id bigint generated by default as identity primary key,
  strategy_id text not null,
  status text not null,
  positions_open integer not null default 0,
  trades_closed integer not null default 0,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

revoke all on ai_trade.training_arena_positions from anon,authenticated;
revoke all on ai_trade.training_arena_trades from anon,authenticated;
revoke all on ai_trade.training_arena_journal from anon,authenticated;
revoke all on ai_trade.training_arena_runs from anon,authenticated;

do $$
declare j bigint;
begin
  select jobid into j from cron.job where jobname='ai-trade-training-arena-daily' limit 1;
  if j is not null then perform cron.unschedule(j); end if;
end $$;

select cron.schedule(
  'ai-trade-training-arena-daily',
  '35 3 * * *',
  $cron$
  select net.http_post(
    url := 'https://oziktadfeenydvgobudr.supabase.co/functions/v1/ai-trade-training-arena',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'x-ai-trade-cron',(select secret from ai_trade.cron_auth where id=1)
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 120000
  );
  $cron$
);
